{
 "title": "My First Dashboard",
 "time": { "from": "2026-03-27T07:25:33.833Z", "to": "2026-03-27T19:25:33.833Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"python-api\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"python-api\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"python-api\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m]))"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"python-api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "up{job=\"python-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}