"""
HTTP metrics middleware.

This middleware records Prometheus metrics for every incoming HTTP request.

Recorded metrics:
- http_requests_total
- http_request_duration_seconds
- http_errors_total

Design notes:
- Metrics are collected centrally in middleware so all routes are covered.
- Route labels use the normalized FastAPI route template when available
  (for example: /events/{event_id}) to avoid high-cardinality metrics.
- The /metrics endpoint is excluded to prevent Prometheus self-scrape traffic
  from polluting normal API metrics.
"""

from __future__ import annotations

import time

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

from app.core.metrics import (
    HTTP_ERRORS_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
)

EXCLUDED_ROUTES = {"/metrics", "/docs", "/openapi.json", "/redoc"}

class MetricsMiddleware(BaseHTTPMiddleware):
    """
    Middleware for collecting Prometheus HTTP metrics.

    Metrics recorded:
    - Total request count
    - Request latency
    - Error count

    Labels used:
    - method
    - route
    - status_code

    Why middleware:
    - Ensures every request is measured in one place
    - Keeps instrumentation consistent
    - Avoids duplicating metric logic in every endpoint
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        """
        Process the incoming request, capture timing and status code,
        then record Prometheus metrics.

        Args:
            request: The incoming HTTP request.
            call_next: The next ASGI handler in the middleware chain.

        Returns:
            The HTTP response generated by downstream handlers.

        Raises:
            Re-raises any downstream exception after recording a 500 status
            for metrics purposes.
        """
        start_time = time.perf_counter()
        method = request.method
        status_code = 500

        try:
            response = await call_next(request)
            status_code = response.status_code
            return response

        except Exception:
            # If an exception escapes downstream, treat it as a server error
            # for metrics. The exception handler layer will decide the final
            # HTTP response returned to the client.
            status_code = 500
            raise

        finally:
            route = self._get_route_template(request)

            # Avoid recording Prometheus scraping traffic as normal API traffic.
            if route not in EXCLUDED_ROUTES:
                duration = time.perf_counter() - start_time

                HTTP_REQUESTS_TOTAL.labels(
                    method=method,
                    route=route,
                    status_code=str(status_code),
                ).inc()

                HTTP_REQUEST_DURATION_SECONDS.labels(
                    method=method,
                    route=route,
                ).observe(duration)

                if status_code >= 400:
                    HTTP_ERRORS_TOTAL.labels(
                        method=method,
                        route=route,
                        status_code=str(status_code),
                    ).inc()

    @staticmethod
    def _get_route_template(request: Request) -> str:
        """
        Resolve the normalized route template for the request.

        FastAPI attaches the matched route object to the ASGI scope after
        routing. When available, using route.path gives stable labels such as
        /events/{event_id} instead of raw paths like /events/123.

        Falls back to the raw request path if route metadata is unavailable.

        Args:
            request: The incoming HTTP request.

        Returns:
            A normalized route template string when possible, otherwise the
            raw request path.
        """
        route = request.scope.get("route")

        if route is not None and hasattr(route, "path"):
            return route.path

        return request.url.path